### PR TITLE
fix: don't fail when repo url is not github

### PR DESCRIPTION
**Pull request by evilebottnawi**
@wooorm friendly ping
Fix https://github.com/wooorm/remark-validate-links/issues/16

### CODE REVIEW

**Comment by wooorm** [comment]
👋

1. Why are you running remark-validate-links, if the repo is not supported?
2. Shouldn’t we try to add support for gitlab repos?
3. Would it make sense to throw an error on unsupported repos?

**Comment by evilebottnawi** [comment]
1. I have one remark preset for all repos, also which outside from `github`, yep i can disable plugin (now it is workaround), but we can just `return` and avoid this problem. I have a common repo with configuration (linters, presets, editorconfig and etc) and I'm synchronizing it with all the repositories (include `github` and `gitlab` and other) and I would not want to have different configurations for different types where stored repositories.
2. It is be great, but need implement `gitlab` package, we can do it in future :+1: 
3. Maybe, but it is also fix other problem (look https://github.com/zeke/github-url-to-object/blob/master/index.js#L42 https://github.com/zeke/github-url-to-object/blob/master/index.js#L50), we can have broken url in `package.json` or passed throw CLI.

**Comment by wooorm** [comment]
> 2. It is be great, but need implement gitlab package, we can do it in future 👍

Really? Is it that hard? For GH support, there’s no `github` package used either?

> 3. Maybe, but it is also fix other problem (look https://github.com/zeke/github-url-to-object/blob/master/index.js#L42 https://github.com/zeke/github-url-to-object/blob/master/index.js#L50), we can have broken url in package.json.

We should probably throw a nice error on those, not just exit cleanly?

**Comment by evilebottnawi** [comment]
@wooorm 
2. I don't known maybe it is not hard, just don't have time for this now :disappointed: 
3. Ok, let's throw error :+1:

**Comment by wooorm** [comment]
No, it’s not hard. There’s only a few lines of code involved. There’s no network connection needed for `remark-validate-links`, just the file-system is accessed.

Could you provide me a list of valid `repository` settings in `package.json` for GitLab projects? `gitlab:<gitlabname>/<gitlabrepo>`, what else?

**Comment by evilebottnawi** [comment]
@wooorm seems only `gitlab:<gitlabname>/<gitlabrepo>`

**Comment by wooorm** [comment]
I added proper support for GitLab (which was easy) and Bitbucket (which was hard), which should be published in a few minutes!

**Comment by evilebottnawi** [comment]
@wooorm thanks!

**Pull request closed without merging**
